control_statement: error
cyclomatic_complexity: 12
file_length: 
  warning: 550
force_cast: warning
force_try: warning
function_body_length:
  warning: 80
function_parameter_count: 8
identifier_name:
  min_length:
    error: 3
  excluded:
    - i
    - j
    - x
    - x1
    - x2
    - y
    - y1
    - y2
    - dx
    - dy
    - id
    - to
    - up
line_length:
  warning: 150
  ignores_interpolated_strings: true
  ignores_urls: true
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
type_body_length: 
  warning: 300
type_name:
  min_length:
    error: 3
  max_length:
    warning: 45
    error: 50

included:
  - RedditAPI

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - file_name_no_space
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - operator_usage_whitespace
  - prefer_self_type_over_type_of_self
  - private_action
  - sorted_imports
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unused_declaration
  - unused_import
  - vertical_whitespace_between_cases

custom_rules:
  type_safe_font:
    included: ".*\\.swift"
    name: "Prefer Defined Fonts"
    regex: "UIFont\\(name:*\\s\\\".+\\\""
    message: "Use Fonts.fontName instead of UIFont(named: \"String\")"
    severity: warning
  explicit_uialert_actions:
    included: ".*\\.swift"
    name: "Prefer explit actions"
    regex: "addAction\\(UIAlertAction"
    message: "Break out the UIAlertAction creation and pass it to the addAction function."
    severity: warning
  explicit_alert_actions:
    included: ".*\\.swift"
    name: "Prefer explit actions"
    regex: "addAction\\(AlertAction"
    message: "Break out the AlertAction creation and pass it to the addAction function."
    severity: warning
  grouped_imports:
    included: ".*\\.swift"
    name: "Group import statements"
    regex: "import.+\n\nimport"
    message: "All import statements should be grouped"
    severity: error

excluded:
  - Pods
  - Rachio/Generated
  - ThirdParty/

# TODO: these are temporarily disabled. Delete as needed
disabled_rules:
- todo
- function_body_length
- type_body_length
- closure_body_length
- valid_ibinspectable